version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: yarn

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install-npm-packages in demo
          command: cd demo && yarn install

      - run:
          name: install-npm-packages
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Run Linting"
          command: npm run lint
