const dataTypes = {
    "STRING": "string",
    "STRING(1234)": "string",
    "STRING.BINARY": "string",
    "TEXT": "string",
    "TEXT('tiny')": "string",
    "CITEXT": "string",
    "INTEGER": "number",
    "BIGINT": "number",
    "BIGINT(11)": "number",
    "FLOAT": "number",
    "FLOAT(11)": "number",
    "FLOAT(11, 10)": "number",
    "REAL": "number",
    "REAL(11)": "number",
    "REAL(11, 12)": "number",
    "DOUBLE": "number",
    "DOUBLE(11)": "number",
    "DOUBLE(11, 10)": "number",
    "DECIMAL": "number",
    "DECIMAL(10, 2)": "number",
    "DATE": "date",
    "DATE(6)": "date",
    "DATEONLY": "date",
    "BOOLEAN": "boolean",
    "ENUM('value 1', 'value 2')": "any",
    // "ARRAY(Sequelize.TEXT)": "",
    // "ARRAY(Sequelize.ENUM)": "",
    "JSON": "object",
    // "JSONB": "",
    "BLOB": "string",
    "BLOB('tiny')": "string",
    // "UUID": "",
    // "CIDR": "",
    // "INET": "",
    // "MACADDR": "",
    // "RANGE(Sequelize.INTEGER)": "",
    // "RANGE(Sequelize.BIGINT)": "",
    // "RANGE(Sequelize.DATE)": "",
    // "RANGE(Sequelize.DATEONLY)": "",
    // "RANGE(Sequelize.DECIMAL)": "",
    // "ARRAY(Sequelize.RANGE(Sequelize.DATE))": "",
    // "GEOMETRY": "",
    // "GEOMETRY('POINT')": "",
    // "GEOMETRY('POINT', 4326)": ""
}

module.exports = dataTypes;